Task1 - Create ToDoList with share instance
olegmyatlikov/ToDoList pull request #2
Opened 2017-06-28 16:10 UTC by olegmyatlikov

2017-06-28 22:40 UTC, imironenko requested changes

2017-06-28 22:40 UTC, imironenko commented on ToDoList/AppDelegate.h
> +@property (strong, nonatomic) UINavigationBar *bar;
для чего используется ?

2017-06-28 22:40 UTC, imironenko commented on ToDoList/OMMDatepickerViewController.m
> +    [self.delegate showTabBar];
нет надобности в этом методе, реализацию данного метода можно выполнить в `setDateFromDatePickerVC:date:`

2017-06-28 22:40 UTC, imironenko commented on ToDoList/OMMDatepickerViewController.m
> +    [self.delegate showTabBar];
аналогично

2017-06-28 22:40 UTC, imironenko commented on ToDoList/OMMInboxTableViewController.m
> +    self.taskService = [OMMTaskService sharedInstance];
нет надобности хранить синглтон

2017-06-28 22:40 UTC, imironenko commented on ToDoList/OMMInboxTableViewController.m
> +    self.taskArrayDirection = (self.isTasksArrayDirectionReverse) ? NO : YES; // save direction condition
`self.isTasksArrayDirectionReverse` возвращает буловское значение

2017-06-28 22:40 UTC, imironenko commented on ToDoList/OMMInboxTableViewController.m
> +        } else if ([[[tasksSortedByStartDate[i] valueForKey:OMMInboxStartDateTasksProperty] convertToStringForCompareDate] isEqual:[[tasksSortedByStartDate[i-1] valueForKey:OMMInboxStartDateTasksProp
давай не использовать valueForKey для nsdictionary

2017-06-28 22:40 UTC, imironenko commented on ToDoList/OMMInboxTableViewController.m
> +    } else {
нет нужды в else, давай возвращать как значение по умолчанию

2017-06-28 22:40 UTC, imironenko commented on ToDoList/OMMInboxTableViewController.m
> +    } else {
нет нужды в else

2017-06-28 22:40 UTC, imironenko commented on ToDoList/OMMTaskCell.m
> +- (void)awakeFromNib {
не используемые методы стоит удалить

2017-06-29 09:45 UTC, olegmyatlikov commented on ToDoList/OMMInboxTableViewController.m
> +    self.taskArrayDirection = (self.isTasksArrayDirectionReverse) ? NO : YES; // save direction condition
А что тут не так? Я Меняю булонское значение на противоположное в этом методе. Если массив перевернут, то после выполнения метода переворачивания меняю проперти на "не перевернут"

2017-06-29 11:01 UTC, olegmyatlikov commented on ToDoList/OMMInboxTableViewController.m
> +    self.taskService = [OMMTaskService sharedInstance];
Ты имеешь в виду перенести "self.taskService = [OMMTaskService sharedInstance];" туда, где мне понадобится?

2017-06-29 22:51 UTC, imironenko requested changes

2017-06-29 22:51 UTC, imironenko commented on ToDoList/OMMDatepickerViewController.h
> +- (void)showTabBar;
в этом методе нет необходимости, обработку мы можем делать в `setDateFromDatePickerVC:date:`
стоит убрать его везде

2017-06-29 22:51 UTC, imironenko commented on ToDoList/OMMTask.h
> +typedef enum TaskPriority{
enum следует привести к код стайлу и константные значения для enum  можно сделать следующим способом
```
static NSString *const OMMTaskPriorityString[OMMTaskPriorityCount] = {
    [OMMTaskPriorityNone] = @"none",
    [OMMTaskPriorityLow] = @"low",
    [OMMTaskPriorityMedium] = @"medium",
    [OMMTaskPriorityHigh] = @"High"
};
```

2017-07-03 20:29 UTC, imironenko approved these changes
👍

2017-07-04 15:38 UTC, merged