Task2.0.1 core data
olegmyatlikov/ToDoList pull request #7
Opened 2017-07-23 19:04 UTC by olegmyatlikov

2017-08-08 21:30 UTC, imironenko requested changes

2017-08-08 21:30 UTC, imironenko commented on ToDoList/OMMDataManager.m
> +- (OMMTask *)getTaskByID:(NSNumber *)taskID {
не стоит использовать префикс `get`
аналогично для всех остальных методов

2017-08-08 21:30 UTC, imironenko commented on ToDoList/OMMSearchTableViewController.m
> +    self.activeTasksPredicate = [NSPredicate predicateWithFormat:@"closed = %@", [NSNumber numberWithBool:NO]];
лучше упростить `[NSPredicate predicateWithFormat:@"closed == NO"];`

2017-08-08 21:30 UTC, imironenko commented on ToDoList/OMMSearchTableViewController.m
> +    self.closedTasksPredicate = [NSPredicate predicateWithFormat:@"closed = %@", [NSNumber numberWithBool:YES]];
аналогично

2017-08-09 07:31 UTC, olegmyatlikov commented
Поправил

https://github.com/olegmyatlikov/ToDoList/pull/7 <https://github.com/olegmyatlikov/ToDoList/pull/7>


> On 9 Aug 2017, at 00:30, Igor Mironenko <notifications@github.com> wrote:
> 
> @imironenko requested changes on this pull request.
> 
> In ToDoList/OMMDataManager.m <https://github.com/olegmyatlikov/ToDoList/pull/7#discussion_r132036085>:
> 
> > +    OMMTask *task = [self getTaskByID:taskID];
> +    [self.managedObjectContext deleteObject:task];
> +    
> +    [self cancelLocalNotificationForTask:task]; // delete notification if task was removed
> +    [self saveContext];
> +}
> +
> +- (void)closeTaskByID:(NSNumber *)taskID {
> +    OMMTask *task = [self getTaskByID:taskID];
> +    task.closed = [NSNumber numberWithBool:YES];
> +    
> +    [self cancelLocalNotificationForTask:task]; // delete notification if task was removed
> +    [self saveContext];
> +}
> +
> +- (OMMTask *)getTaskByID:(NSNumber *)taskID {
> не стоит использовать префикс get
> аналогично для всех остальных методов
> 
> In ToDoList/OMMSearchTableViewController.m <https://github.com/olegmyatlikov/ToDoList/pull/7#discussion_r132037718>:
> 
> > @@ -53,10 +51,10 @@ + (void)initialize {
>  - (void)viewDidLoad {
>      [super viewDidLoad];
>      
> -    self.activeTasksPredicate = [NSPredicate predicateWithFormat:OMMsearchTaskIsOpen];
> -    self.closedTasksPredicate = [NSPredicate predicateWithFormat:OMMsearchTaskIsClosed];
> +    self.activeTasksPredicate = [NSPredicate predicateWithFormat:@"closed = %@", [NSNumber numberWithBool:NO]];
> лучше упростить [NSPredicate predicateWithFormat:@"closed == NO"];
> 
> In ToDoList/OMMSearchTableViewController.m <https://github.com/olegmyatlikov/ToDoList/pull/7#discussion_r132037867>:
> 
> > @@ -53,10 +51,10 @@ + (void)initialize {
>  - (void)viewDidLoad {
>      [super viewDidLoad];
>      
> -    self.activeTasksPredicate = [NSPredicate predicateWithFormat:OMMsearchTaskIsOpen];
> -    self.closedTasksPredicate = [NSPredicate predicateWithFormat:OMMsearchTaskIsClosed];
> +    self.activeTasksPredicate = [NSPredicate predicateWithFormat:@"closed = %@", [NSNumber numberWithBool:NO]];
> +    self.closedTasksPredicate = [NSPredicate predicateWithFormat:@"closed = %@", [NSNumber numberWithBool:YES]];
> аналогично
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/olegmyatlikov/ToDoList/pull/7#pullrequestreview-55075755>, or mute the thread <https://github.com/notifications/unsubscribe-auth/APJBjN5M-gJ89ptvGxsPM7ehmWhqhbMsks5sWNNigaJpZM4OgigE>.
>

2017-08-10 08:55 UTC, imironenko approved these changes
👍

2017-08-14 12:43 UTC, merged